InternTasks-3A
keremmimir/InternTasks-3A pull request #1
Opened 2024-07-28 13:12 UTC by keremmimir

2024-07-28 14:36 UTC, keremmimir commented
UI Controller (Fragment) içerisinde tutulan değişkenler, cihaz döndürüldüğünde veya yeniden yaratıldığında kaybolur çünkü Fragment yeniden oluşturulur. Bu yüzden cihazı döndürdüğümüzde sayaç değeri sıfırlanır.
ViewModel, konfigürasyon değişikliklerinde verilerin korunmasını sağlar. Fragment'ta ViewModel kullanarak, sayacı arttırdıktan sonra cihazı döndürdüğümüzde değer korunur.

2024-07-29 12:33 UTC, keremmimir commented
LiveData, verilerde bir değişiklik olduğunda otomatik olarak güncellenir. Bu, veri değişikliklerini elle kontrol etme gereğini ortadan kaldırır ve kullanıcı arayüzü ile veri arasında doğrudan bir bağ sağlar. Buda bize kodun daha temiz ve daha anlaşılır olmasını sağlar. Ayrıca LiveData, ekran döndürmeleri ve diğer yapılandırma değişiklikleri sırasında verilerin korunmasına yardımcı olur.

2024-07-29 14:22 UTC, keremmimir commented
**Activity Scope (activityViewModels() ile paylaşılan ViewModel):** 
activityViewModels() kullanarak Activity scope'unda bir ViewModel oluştururuz. Bu ViewModel, Activity'nin yaşam döngüsü boyunca korunur ve Activity'ye bağlı tüm fragment'lar arasında paylaşılır.
Fragment'lar arasında veri paylaşımını ve tutarlılığını sağlar. Ancak bağımlılık yaratabilir ve yönetimi zor olabilir.

**Fragment Scope (viewModels()):** Her fragment için izole veri yönetimi sağlar. Veri paylaşımı zorlaşır.

**Application Scope (Uygulama genelinde paylaşılan ViewModel)**: Uygulama genelinde veri paylaşımı sağlar. Yönetimi karmaşıktır ve bellek sızıntısı riski taşır.

2024-08-05 08:49 UTC, aliosmanay requested changes
eline saglik ufak bir kac yorumum oldu 🚀

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/java/com/example/interntasks_3a/CounterFragment.kt
> +        binding.switch1.setOnCheckedChangeListener { _, isChecked ->
binding icin kotlin scope functions ile yalinlastirma yapabiliriz

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/java/com/example/interntasks_3a/NumberGuessFragment.kt
> +            binding.guessText.text = "TEKRAR DENE"
bunu string.xml den alabiliriz

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/java/com/example/interntasks_3a/NumberGuessFragment.kt
> +        binding.charText.setOnClickListener {
kotlin scope function ile daha sade hale getirebiliriz

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/java/com/example/interntasks_3a/NumberGuessViewModel.kt
> +            result.value = "KAZANDIN!!"
string.xml den alabiliriz.

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/java/com/example/interntasks_3a/NumberGuessViewModel.kt
> +        number.value = random
LiveData`yi guncellerken setValue() ve postValue() farklarina bakalim, burada hangisi uygunsa onu kullanalim.

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/res/layout/activity_number_guess.xml
> +        android:layout_width="match_parent"
0dp verebiliriz

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/res/layout/activity_number_guess.xml
> +        android:layout_height="match_parent"
0dp verebiliriz

2024-08-05 08:49 UTC, aliosmanay commented on app/src/main/res/layout/fragment_number_guess.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
burada linear layout kullanilabilir ama bu ikinci layout a gerek olmadan root layout yani tek ConstrainLayout icinde constrainLayout un flow ozelligini deneyebilirsin. Chain ile ikinci bir constrainLayout a ihtiyac olmadan da olabilir belki bi ugrasalim :)

2024-08-09 10:45 UTC, aliosmanay approved these changes

2024-08-10 13:35 UTC, merged